"use client";
import {ArrowLeft,ArrowUpRight} from "lucide-react";
import Link from "next/link";
import {Header,Footer} from "../components";

export default function Page(){
 const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const text=`Hola Stahlé, quiero cotizar un diseño personalizado.\n\nNombre: ${f.get("nombre")}\nTipo de mueble: ${f.get("tipo")}\nMedidas: ${f.get("medidas")||"Por definir"}\nUbicación: ${f.get("ubicacion")}\nDescripción: ${f.get("descripcion")}`;window.open(`https://wa.me/50247379912?text=${encodeURIComponent(text)}`,"_blank")};
 return <main><Header/><section className="quote-page"><div className="quote-intro"><Link href="/" className="back"><ArrowLeft size={16}/> Inicio</Link><p className="kicker">DISEÑO PERSONALIZADO</p><h1>Cuéntanos la idea.<br/><em>Nosotros le damos forma.</em></h1><p>Completa los datos básicos y continúa por WhatsApp. Allí podrás enviarnos fotografías, referencias y cualquier detalle adicional.</p><div className="steps"><span>01 <b>Cuéntanos tu idea</b></span><span>02 <b>Envíanos referencias por WhatsApp</b></span><span>03 <b>Recibe tu propuesta</b></span></div></div><form className="quote-form" onSubmit={submit}><label>¿Cómo te llamas?<input name="nombre" required placeholder="Tu nombre"/></label><div className="form-row"><label>¿Qué necesitas?<select name="tipo" required defaultValue=""><option value="" disabled>Elige una opción</option><option>Mesa de centro</option><option>Mesa de comedor</option><option>Consola</option><option>Mueble para televisión</option><option>Estantería</option><option>Vinera o mueble bar</option><option>Mueble para oficina</option><option>Otro</option></select></label><label>¿Dónde se entregaría?<input name="ubicacion" required placeholder="Ciudad y municipio"/></label></div><label>Medidas aproximadas <small>(opcional)</small><input name="medidas" placeholder="Ej. 120 × 60 × 40 cm"/></label><label>Cuéntanos brevemente tu idea<textarea name="descripcion" required rows={4} placeholder="Materiales, color, estilo o cómo te gustaría que fuera..."/></label><button className="btn gold" type="submit">Continuar por WhatsApp <ArrowUpRight size={17}/></button><small>Al abrirse WhatsApp podrás adjuntar imágenes directamente en el chat.</small></form></section><Footer/></main>
}
