import {ArrowDown,ArrowRight,ArrowUpRight,Sparkles} from "lucide-react";
import {Header,Footer} from "./components";
import {collections,rooms,products,heroImage} from "./data";
export default function Home(){return <main><Header/>
<section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(7,6,5,.96) 0%,rgba(7,6,5,.84) 31%,rgba(7,6,5,.30) 62%,rgba(7,6,5,.08)),url('${heroImage}')`}}><div className="hero-content"><p className="kicker">DISEÑO Y FABRICACIÓN EN GUATEMALA</p><h1>Diseño con carácter.<br/><em>Hecho para durar.</em></h1><p>Diseñamos y fabricamos muebles a medida combinando metal, madera, vidrio y mármol para crear espacios modernos con identidad.</p><div className="actions"><a className="btn gold" href="#colecciones">Explorar colecciones</a><a className="hero-link" href="/cotizar">Cotizar un diseño <ArrowUpRight size={14}/></a></div></div><a className="scroll" href="#ambientes">DESCUBRIR <ArrowDown size={15}/></a></section>
<section id="ambientes" className="section rooms-section"><div className="room-glow"/><div className="section-head"><div><p className="kicker">EXPLORA A TU MANERA</p><h2>Una pieza para<br/><em>cada espacio.</em></h2></div><div className="rooms-intro"><span>01 — 06</span><p>Selecciona un ambiente para descubrir muebles pensados para su ritmo, función y proporciones.</p></div></div><div className="marquee"><div className="marquee-track">{[...rooms,...rooms].map((r,i)=><a className="room-card" href={`/ambientes/${r.slug}`} key={`${r.slug}-${i}`} style={{backgroundImage:`linear-gradient(0deg,rgba(8,7,6,.94),rgba(8,7,6,.08) 72%),url('${r.image}')`}}><span className="room-number">0{(i%rooms.length)+1}</span><div className="room-label"><small>{r.detail}</small><span>{r.name}</span></div><b><ArrowRight/></b></a>)}</div></div><div className="room-rule"><span>DESLIZA PARA EXPLORAR</span><i/></div></section>
<section id="colecciones" className="section collections-section"><div className="section-head"><div><p className="kicker">COLECCIONES STAHLÉ</p><h2>Cuatro colecciones.<br/><em>Una misma esencia.</em></h2></div><p>Cada colección identifica una combinación de materiales diferente. Elige la que mejor se adapte a tu espacio.</p></div><div className="collection-grid">{collections.map((c,i)=><a href={`/colecciones/${c.slug}`} className="collection-card" key={c.slug}><div className="collection-image" style={{backgroundImage:`linear-gradient(0deg,rgba(8,7,6,.9),transparent 68%),url('${c.image}')`}}><span className="collection-number">0{i+1}</span><div><small>COLECCIÓN</small><h3>{c.name}</h3><p>{c.eyebrow}</p></div></div><div className="collection-copy"><p>{c.description}</p><span>Explorar {c.name} <ArrowRight size={16}/></span></div></a>)}</div></section>
<section className="section featured"><div className="section-head"><div><p className="kicker">PIEZAS SELECCIONADAS</p><h2>Descubre piezas<br/><em>para hacerlas tuyas.</em></h2></div><p>Una selección de diseños representativos de Stahlé. Cada pieza puede adaptarse en medidas, materiales y acabados.</p></div><div className="selected-grid">{products.slice(0,3).map(p=>{const c=collections.find(item=>item.slug===p.collection);return <a className="selected-card" href={`/producto/${p.slug}`} key={p.slug}><div className="selected-image"><img src={p.images[0]} alt={p.name}/><span>{p.status.toUpperCase()}</span></div><div className="selected-meta"><p>{p.type} · {c?.name}</p><h3>{p.name}</h3><small>{p.materials.slice(1).join(" · ")}</small><div><b>{p.price}</b><span>Ver pieza <ArrowRight size={16}/></span></div></div></a>})}</div></section>
<section className="custom-design"><div><Sparkles/><p className="kicker">HECHO PARA TI</p><h2>¿Tienes una idea<br/><em>que aún no existe?</em></h2><p>Envíanos tu referencia, medidas aproximadas y el espacio donde vivirá. Nosotros convertimos la idea en una pieza fabricable.</p><a className="btn gold" href="/cotizar">Cotizar mi diseño</a></div></section>
<section id="nosotros" className="section about"><div className="about-heading"><div><p className="kicker">NOSOTROS</p><h2>Diseñamos piezas<br/><em>con carácter.</em></h2></div><div className="about-story"><p>Stahlé nace para crear mobiliario que una diseño y fabricación en una misma pieza. Trabajamos el metal junto a madera, vidrio y piedra para convertir ideas en muebles con presencia, función e identidad.</p><blockquote>“Materiales honestos, proporciones cuidadas y piezas creadas para espacios reales.”</blockquote></div></div><div className="about-pillars"><article><span>01</span><h3>Diseño con intención</h3><p>Cada línea, proporción y material responde al espacio y a la función que tendrá la pieza.</p></article><article><span>02</span><h3>Fabricación precisa</h3><p>Convertimos cada diseño en una estructura coherente, estable y pensada para durar.</p></article><article><span>03</span><h3>Personalización real</h3><p>Adaptamos medidas, materiales y acabados para crear una pieza que se sienta verdaderamente tuya.</p></article></div><div className="about-signature"><p>DISEÑADO Y FABRICADO EN GUATEMALA</p><a className="about-link" href="/cotizar">Cotizar un proyecto <ArrowRight size={16}/></a></div></section><Footer/></main>}
