"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, Save, Trash2, Upload, Star } from "lucide-react";
import { products as catalog } from "../../data";

type Product={id:string;name:string;description?:string;collection:string;room:string;materials?:string[];dimensions?:string;price?:string;images?:string[]};

export default function EditProductPage({params}:{params:Promise<{id:string}>}) {
 const [product,setProduct]=useState<Product|null>(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(""); const [files,setFiles]=useState<File[]>([]);
 useEffect(()=>{params.then(({id})=>fetch("/api/admin/products").then(r=>r.ok?r.json():[]).then((items:Product[])=>{const found=items.find(x=>x.id===id) ?? catalog.find(x=>x.slug===id); if(found)setProduct({id:found.id??found.slug,name:found.name,description:found.description,collection:found.collection,room:found.room,materials:found.materials,dimensions:found.dimensions,price:found.price,images:found.images}); setLoading(false)}).catch(()=>setLoading(false))},[params]);
 const update=(key:keyof Product,value:string)=>setProduct(p=>p?{...p,[key]:value}:p);
 const save=async(e:React.FormEvent)=>{e.preventDefault(); if(!product)return; setMessage(""); const uploaded:string[]=[]; for(const file of files){const form=new FormData();form.append("file",file);const r=await fetch("/api/admin/images",{method:"POST",body:form});if(r.ok)uploaded.push((await r.json()).url)} const body={...product,materials:typeof product.materials==="string"?String(product.materials).split(",").map(x=>x.trim()).filter(Boolean):product.materials,images:[...uploaded,...(product.images??[])]}; const r=await fetch("/api/admin/products",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); setMessage(r.ok?"Cambios guardados correctamente.":"No se pudieron guardar los cambios."); if(r.ok)setProduct({...product,images:body.images});};
 const remove=async()=>{if(!product||!confirm("¿Eliminar este producto?"))return;const r=await fetch("/api/admin/products?id="+encodeURIComponent(product.id),{method:"DELETE"});if(r.ok)window.location.href="/admin";};
 if(loading)return <main className="admin-edit-page"><p>Cargando producto…</p></main>;
 if(!product)return <main className="admin-edit-page"><p>No se encontró el producto.</p><a href="/admin">Volver al panel</a></main>;
 return <main className="admin-edit-page"><a className="admin-back-link" href="/admin"><ArrowLeft size={16}/>Volver a la galería</a><div className="admin-edit-header"><div><p className="admin-eyebrow">EDITOR DE PRODUCTO</p><h1>Editar producto</h1></div><button className="admin-delete admin-delete-large" type="button" onClick={remove}><Trash2 size={16}/>Eliminar producto</button></div><form className="admin-edit-layout" onSubmit={save}><section className="admin-edit-gallery"><div className="admin-edit-main-image">{product.images?.[0]?<img src={product.images[0]} alt={product.name}/>:<div><Upload size={28}/><span>Sin portada</span></div>}</div><div className="admin-edit-thumbs">{(product.images??[]).map((url,i)=><div key={url} className={i===0?"active":""}><img src={url} alt={`Foto ${i+1}`}/>{i===0&&<span><Star size={11}/>Portada</span>}</div>)}<label className="admin-add-photo"><Upload size={20}/><span>Agregar fotos<input type="file" accept="image/*" multiple onChange={e=>setFiles(Array.from(e.target.files??[]))}/></span></label></div></section><section className="admin-edit-fields"><label>Nombre<input value={product.name} onChange={e=>update("name",e.target.value)} required/></label><label>Descripción<textarea rows={6} value={product.description??""} onChange={e=>update("description",e.target.value)}/></label><div className="admin-edit-row"><label>Colección<select value={product.collection} onChange={e=>update("collection",e.target.value)}><option value="obsidian">Obsidian</option><option value="savia">Savia</option><option value="aurea">Áurea</option><option value="vertice">Vértice</option></select></label><label>Ambiente<select value={product.room} onChange={e=>update("room",e.target.value)}><option value="sala">Sala</option><option value="comedor">Comedor</option><option value="dormitorio">Dormitorio</option><option value="cocina">Cocina</option><option value="bano">Baño</option><option value="oficina">Oficina</option></select></label></div><label>Materiales<input value={(product.materials??[]).join(", ")} onChange={e=>update("materials",e.target.value)}/></label><label>Medidas<input value={product.dimensions??""} onChange={e=>update("dimensions",e.target.value)}/></label><label>Precio<input value={product.price??""} onChange={e=>update("price",e.target.value)}/></label><button className="admin-primary admin-save-button" type="submit"><Save size={17}/>Guardar cambios</button>{message&&<p className="admin-success">{message}</p>}</section></form></main>;
}
